services:
  - type: web
    name: inventario-web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Inventario
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: "base64:9zsVb5+YgPvilBv6Qq52+4Q2WpOIwwqrDaR4l886XWc="
      - key: APP_URL
        value: https://inventario-web-on8a.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-12f6387d-javipez1999-ca54.f.aivencloud.com
      - key: DB_PORT
        value: "20117"
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: "AQUI_VA_LA_CONTRASEÑA_REAL_DE_AIVEN"
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
      - key: DB_SSL_VERIFY_SERVER_CERT
        value: "false"
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_CHANNEL
        value: stderr
